spring:
  application:
    name: auth-service
  config:
    import: configserver:http://localhost:8888/
  profiles:
    active: jwt, kafka, mongo, service-details
  cloud:
    config:
      fail-fast: true
