version: '3.8'

services:
  kafka:
    image: wurstmeister/kafka
    container_name: "kafka"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongousr
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongopwd
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_OPTIONS_EDITORTHEME=dark
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    restart: always
    networks:
      - mongo_network

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongousr
      - MONGO_INITDB_ROOT_PASSWORD=mongopwd
    volumes:
      - D:\db\instaMongo:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo_network

  neo4j:
    image: neo4j
    ports:
      - 7687:7687
      - 7474:7474

  cassandra:
    image: cassandra
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - D:\db\instaCassandra:/var/lib/cassandra

networks:
  mongo_network:
    driver: bridge

volumes:
  mongodb_vol: