spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
             allowed-origins: "http://localhost:3000"
             allowed-headers: "*"
             allowed-methods:
               - GET
               - POST
               - PUT
               - DELETE
    config:
      fail-fast: true

info:
  app:
    name: gateway-server
    description: gateway-server for instagram clone app
    version: 0.0.1
