spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      fail-fast: true

info:
  app:
    name: gateway-server
    description: gateway-server for instagram clone app
    version: 0.0.1
