spring:
  application:
    name: post-service
  profiles:
    active: jwt, kafka, mongo
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      fail-fast: true

logstash:
  host: localhost
  port: 5009
  queue-size: 512