server:
  port: 8001

spring:
  application:
    name: post-service
  data:
    mongodb:
      database: user_posts
      username: mongousr
      password: mongopwd
      port: 27017
      host: localhost
      authentication-database: admin
  cloud:
    stream:
      bindings:
        sendPostChangedEvent-out-0:
          destination: send-post-changed-event
      kafka:
        binder:
          brokers:
            - localhost:9092

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761

security:
  basic:
    enable: false
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: YmFkLXBhc3N3b3JkYmFkLXBhc3N3b3JkYmFkLXBhc3N3b3Jk
