global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'auth'
    metrics_path: '/inst/auth/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8765']
#  - job_name: 'media'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['localhost:8765\inst\media']
#  - job_name: 'post'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['localhost:8765\inst\post']
#  - job_name: 'graph'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['localhost:8765\inst\graph']
#  - job_name: 'feed'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['localhost:8765\inst\feed']