spring:
  application:
    name: media-service
  profiles:
    active: mongo, jwt
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      fail-fast: true

logstash:
  host: localhost
  port: 5009
  queue-size: 512
