server:
  port: 8003

spring:
  application:
    name: feed-service
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic
          insta-auth:
            url: http://localhost:9000
          graph-service:
            url: http://localhost:8082
          post-service:
            url: http://localhost:8001

    function:
      definition: receivePostChangedEvent
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bindings:
        receivePostChangedEvent-in-0:
          destination: post-changed-event
          group: ${spring.application.name}
          content-type: application/json

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

security:
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: 'Bearer '
    expiration: 86400
    secret: YmFkLXBhc3N3b3JkYmFkLXBhc3N3b3JkYmFkLXBhc3N3b3Jk
  service:
    username: d245ef53-5ad5-4216-9c56-89fe0f8302a0
    password: ef919ae4-b893-4969-b782-57978180ad33
