spring:
  application:
    name: feed-service
  profiles:
    active: jwt, kafka, service-details
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      fail-fast: true
