spring:
  application:
    name: feed-service
  profiles:
    active: jwt, kafka, service-details
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      fail-fast: true
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

logstash:
  host: localhost
  port: 5009
  queue-size: 512

management:
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0

info:
  app:
    name: feed-server
    description: feed-server for instagram clone app
    version: 0.0.1