server:
  port: 8003

spring:
  application:
    name: feed-service
  cassandra:
    keyspace-name: insta-feed
    contact-points: localhost
    port: 9042
    schema-action: create_if_not_exists


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

security:
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey

service:
  username: d245ef53-5ad5-4216-9c56-89fe0f8302a0
  password: ef919ae4-b893-4969-b782-57978180ad33

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: BASIC
