apiVersion: 1

deleteDatasources:
    - name: Prometheus
      orgId: 1

datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://prometheus:9090
      access: proxy
      orgId: 1
      editable: true
      jsonData:
          httpMethod: GET